"""create Reviews and add Rating column to Product

Revision ID: 935b0352372e
Revises: baac6011b804
Create Date: 2025-12-31 11:00:54.204714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935b0352372e'
down_revision: Union[str, Sequence[str], None] = 'baac6011b804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM products")
    op.add_column('products', sa.Column('rating', sa.Numeric(precision=1, scale=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
